import { Injectable } from '@angular/core';
import { AngularFirestore, AngularFirestoreCollection } from '@angular/fire/firestore';

@Injectable({
  providedIn: 'root'
})
export class InjectJsonToFirestoreService {
  private _itemsCollection: AngularFirestoreCollection<any>;
  fakeEvents=[
    
      {
          "eventTitle": "vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed",
          "category": 3,
          "reqWeather": "beau",
          "dateBegin": "4/23/2021",
          "dateEnd": "8/14/2020",
          "eventAddress": "31 Steensland Hill",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Croix",
          "eventLat": 47.6252225,
          "eventLong": 0.277316,
          "orgName": "Union Bankshares, Inc.",
          "orgAddress": "93 Lukken Avenue",
          "orgStates": "Haute-Normandie",
          "orgCity": "Le Havre",
          "orgPhone": "867 184 1616",
          "orgMail": "ebahia0@go.com",
          "infoGen": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
          "infoTransp": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 7,
          "media1": "http://dummyimage.com/1623x882.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/926x885.png/dddddd/000000",
          "media3": "http://dummyimage.com/1009x517.png/5fa2dd/ffffff",
          "media4": "http://dummyimage.com/1448x704.png/5fa2dd/ffffff",
          "media5": "http://dummyimage.com/673x959.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/1225x768.png/5fa2dd/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "enim leo rhoncus sed vestibulum sit amet cursus id turpis integer",
          "category": 1,
          "reqWeather": "mauvais",
          "dateBegin": "3/21/2021",
          "dateEnd": "1/10/2021",
          "eventAddress": "991 Gina Way",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Armentières",
          "eventLat": 47.5619629,
          "eventLong": -0.9147447,
          "orgName": "Vedanta  Limited",
          "orgAddress": "81 Northport Circle",
          "orgStates": "Haute-Normandie",
          "orgCity": "Évreux",
          "orgPhone": "490 363 6110",
          "orgMail": "rfeares1@taobao.com",
          "infoGen": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
          "infoTransp": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 14,
          "media1": "http://dummyimage.com/1543x1023.png/dddddd/000000",
          "media2": "http://dummyimage.com/750x626.png/5fa2dd/ffffff",
          "media3": "http://dummyimage.com/1860x659.png/ff4444/ffffff",
          "media4": "http://dummyimage.com/1291x946.png/5fa2dd/ffffff",
          "media5": "http://dummyimage.com/732x736.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/1062x973.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor",
          "category": 5,
          "reqWeather": "neige",
          "dateBegin": "5/8/2020",
          "dateEnd": "3/16/2021",
          "eventAddress": "70847 Loeprich Junction",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Roubaix",
          "eventLat": 50.6930818,
          "eventLong": 3.1845673,
          "orgName": "Apogee Enterprises, Inc.",
          "orgAddress": "612 Hovde Street",
          "orgStates": "Haute-Normandie",
          "orgCity": "Le Havre",
          "orgPhone": "150 270 0251",
          "orgMail": "sbacchus2@wordpress.com",
          "infoGen": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
          "infoTransp": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 16,
          "media1": "http://dummyimage.com/1636x916.png/cc0000/ffffff",
          "media2": "http://dummyimage.com/1692x709.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1667x671.png/ff4444/ffffff",
          "media4": "http://dummyimage.com/1590x873.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/894x789.png/5fa2dd/ffffff",
          "media6": "http://dummyimage.com/1300x756.png/ff4444/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis",
          "category": 4,
          "reqWeather": "mauvais",
          "dateBegin": "6/15/2020",
          "dateEnd": "4/7/2021",
          "eventAddress": "9537 Mcbride Way",
          "eventStates": "Pays de la Loire",
          "eventCity": "Saint-Jean-de-Monts",
          "eventLat": 46.8260183,
          "eventLong": -2.1318548,
          "orgName": "3D Systems Corporation",
          "orgAddress": "9 Sachtjen Drive",
          "orgStates": "Haute-Normandie",
          "orgCity": "Le Havre",
          "orgPhone": "428 538 3643",
          "orgMail": "pschermick3@abc.net.au",
          "infoGen": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
          "infoTransp": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 32,
          "media1": "http://dummyimage.com/1237x1049.png/5fa2dd/ffffff",
          "media2": "http://dummyimage.com/1734x907.png/5fa2dd/ffffff",
          "media3": "http://dummyimage.com/923x1028.png/5fa2dd/ffffff",
          "media4": "http://dummyimage.com/888x962.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/1481x1034.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/1798x955.png/5fa2dd/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "congue elementum in hac habitasse platea dictumst morbi vestibulum velit id",
          "category": 1,
          "reqWeather": "neige",
          "dateBegin": "6/26/2021",
          "dateEnd": "5/25/2020",
          "eventAddress": "62635 Iowa Plaza",
          "eventStates": "New Jersey",
          "eventCity": "Newark",
          "eventLat": 40.7758541,
          "eventLong": -74.1650991,
          "orgName": "Mesoblast Limited",
          "orgAddress": "13 Norway Maple Pass",
          "orgStates": "Haute-Normandie",
          "orgCity": "Rouen",
          "orgPhone": "973 429 2987",
          "orgMail": "aalexsandrov4@irs.gov",
          "infoGen": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
          "infoTransp": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 93,
          "media1": "http://dummyimage.com/1448x713.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/692x970.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/932x619.png/5fa2dd/ffffff",
          "media4": "http://dummyimage.com/776x883.png/5fa2dd/ffffff",
          "media5": "http://dummyimage.com/1280x723.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/1441x726.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras",
          "category": 5,
          "reqWeather": "beau",
          "dateBegin": "5/15/2021",
          "dateEnd": "2/22/2021",
          "eventAddress": "9814 Buhler Center",
          "eventStates": "Pays de la Loire",
          "eventCity": "Nantes",
          "eventLat": 47.17532,
          "eventLong": -1.6901492,
          "orgName": "Zions Bancorporation",
          "orgAddress": "0364 Arrowood Place",
          "orgStates": "Haute-Normandie",
          "orgCity": "Dieppe",
          "orgPhone": "916 140 8548",
          "orgMail": "seustis5@free.fr",
          "infoGen": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
          "infoTransp": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 87,
          "media1": "http://dummyimage.com/970x493.png/5fa2dd/ffffff",
          "media2": "http://dummyimage.com/1586x697.png/5fa2dd/ffffff",
          "media3": "http://dummyimage.com/871x806.png/dddddd/000000",
          "media4": "http://dummyimage.com/1011x708.png/5fa2dd/ffffff",
          "media5": "http://dummyimage.com/906x817.png/dddddd/000000",
          "media6": "http://dummyimage.com/1166x840.png/5fa2dd/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec",
          "category": 5,
          "reqWeather": "mauvais",
          "dateBegin": "10/1/2020",
          "dateEnd": "10/23/2020",
          "eventAddress": "1780 Morrow Road",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Croix",
          "eventLat": 47.6252225,
          "eventLong": 0.277316,
          "orgName": "PIMCO California Municipal Income Fund III",
          "orgAddress": "7 Sloan Court",
          "orgStates": "Haute-Normandie",
          "orgCity": "Le Havre",
          "orgPhone": "155 916 2924",
          "orgMail": "rcummings6@geocities.jp",
          "infoGen": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
          "infoTransp": "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
          "infoDog": true,
          "infoHandicap": true,
          "infoCost": 21,
          "media1": "http://dummyimage.com/1541x808.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/666x510.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1725x578.png/ff4444/ffffff",
          "media4": "http://dummyimage.com/1767x810.png/ff4444/ffffff",
          "media5": "http://dummyimage.com/1038x721.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/1877x860.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor",
          "category": 5,
          "reqWeather": "neige",
          "dateBegin": "7/3/2020",
          "dateEnd": "5/31/2020",
          "eventAddress": "04951 East Court",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Saint-Laurent-Blangy",
          "eventLat": 50.300542,
          "eventLong": 2.801689,
          "orgName": "Tonix Pharmaceuticals Holding Corp.",
          "orgAddress": "0881 Esker Plaza",
          "orgStates": "Haute-Normandie",
          "orgCity": "Pont-Audemer",
          "orgPhone": "847 361 8697",
          "orgMail": "lkinnett7@unesco.org",
          "infoGen": "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
          "infoTransp": "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 49,
          "media1": "http://dummyimage.com/1390x600.png/5fa2dd/ffffff",
          "media2": "http://dummyimage.com/1421x673.png/dddddd/000000",
          "media3": "http://dummyimage.com/1754x730.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/1273x838.png/ff4444/ffffff",
          "media5": "http://dummyimage.com/1665x578.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/1060x1061.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc",
          "category": 5,
          "reqWeather": "beau",
          "dateBegin": "7/18/2020",
          "dateEnd": "6/12/2020",
          "eventAddress": "84 Bunting Way",
          "eventStates": "Pays de la Loire",
          "eventCity": "Laval",
          "eventLat": 48.0762327,
          "eventLong": -0.7609009,
          "orgName": "Ivy NextShares",
          "orgAddress": "33 Dryden Circle",
          "orgStates": "Basse-Normandie",
          "orgCity": "Alençon",
          "orgPhone": "220 621 2104",
          "orgMail": "damiable8@ucoz.ru",
          "infoGen": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
          "infoTransp": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 71,
          "media1": "http://dummyimage.com/788x819.png/cc0000/ffffff",
          "media2": "http://dummyimage.com/1458x487.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1156x779.png/5fa2dd/ffffff",
          "media4": "http://dummyimage.com/1449x574.png/dddddd/000000",
          "media5": "http://dummyimage.com/1503x935.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/1650x586.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla",
          "category": 3,
          "reqWeather": "mauvais",
          "dateBegin": "1/24/2021",
          "dateEnd": "4/2/2021",
          "eventAddress": "1 Mockingbird Way",
          "eventStates": "Pays de la Loire",
          "eventCity": "Nantes",
          "eventLat": 47.2550409,
          "eventLong": -1.5401497,
          "orgName": "China Jo-Jo Drugstores, Inc.",
          "orgAddress": "722 Dwight Pass",
          "orgStates": "Haute-Normandie",
          "orgCity": "Val-de-Reuil",
          "orgPhone": "822 729 4375",
          "orgMail": "ccitrine9@ibm.com",
          "infoGen": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
          "infoTransp": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
          "infoDog": true,
          "infoHandicap": false,
          "infoCost": 23,
          "media1": "http://dummyimage.com/870x662.png/dddddd/000000",
          "media2": "http://dummyimage.com/1022x1009.png/cc0000/ffffff",
          "media3": "http://dummyimage.com/1104x1046.png/ff4444/ffffff",
          "media4": "http://dummyimage.com/1383x481.png/5fa2dd/ffffff",
          "media5": "http://dummyimage.com/1024x928.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/1366x487.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque",
          "category": 3,
          "reqWeather": "mauvais",
          "dateBegin": "2/15/2021",
          "dateEnd": "1/20/2021",
          "eventAddress": "23 Clove Road",
          "eventStates": "Pays de la Loire",
          "eventCity": "Angers",
          "eventLat": 48.8693156,
          "eventLong": 2.3501981,
          "orgName": "Caterpillar, Inc.",
          "orgAddress": "087 Brentwood Point",
          "orgStates": "Haute-Normandie",
          "orgCity": "Saint-Étienne-du-Rouvray",
          "orgPhone": "542 291 7429",
          "orgMail": "riacobaccia@geocities.jp",
          "infoGen": "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
          "infoTransp": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
          "infoDog": true,
          "infoHandicap": false,
          "infoCost": 15,
          "media1": "http://dummyimage.com/717x860.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1104x704.png/5fa2dd/ffffff",
          "media3": "http://dummyimage.com/1323x561.png/dddddd/000000",
          "media4": "http://dummyimage.com/1845x641.png/5fa2dd/ffffff",
          "media5": "http://dummyimage.com/1663x657.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/1331x556.png/5fa2dd/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit",
          "category": 5,
          "reqWeather": "beau",
          "dateBegin": "7/2/2020",
          "dateEnd": "3/3/2021",
          "eventAddress": "2 Bartelt Junction",
          "eventStates": "Pays de la Loire",
          "eventCity": "La Roche-sur-Yon",
          "eventLat": 46.6704712,
          "eventLong": -1.4244076,
          "orgName": "iShares 20+ Year Treasury Bond ETF",
          "orgAddress": "0783 Nevada Hill",
          "orgStates": "Basse-Normandie",
          "orgCity": "Saint-Lô",
          "orgPhone": "820 700 1534",
          "orgMail": "rslaineyb@ehow.com",
          "infoGen": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
          "infoTransp": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 97,
          "media1": "http://dummyimage.com/870x594.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1518x540.png/cc0000/ffffff",
          "media3": "http://dummyimage.com/1777x487.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/868x675.png/5fa2dd/ffffff",
          "media5": "http://dummyimage.com/1559x942.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/1497x637.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor",
          "category": 2,
          "reqWeather": "mauvais",
          "dateBegin": "2/15/2021",
          "dateEnd": "9/17/2020",
          "eventAddress": "922 Atwood Street",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Marcq-en-Barœul",
          "eventLat": 50.667396,
          "eventLong": 3.0751792,
          "orgName": "Mirati Therapeutics, Inc.",
          "orgAddress": "942 Cottonwood Alley",
          "orgStates": "Haute-Normandie",
          "orgCity": "Yvetot",
          "orgPhone": "156 266 1220",
          "orgMail": "mguilloudc@timesonline.co.uk",
          "infoGen": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
          "infoTransp": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
          "infoDog": true,
          "infoHandicap": false,
          "infoCost": 0,
          "media1": "http://dummyimage.com/1545x509.png/5fa2dd/ffffff",
          "media2": "http://dummyimage.com/1806x695.png/5fa2dd/ffffff",
          "media3": "http://dummyimage.com/1368x841.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/1316x898.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/885x820.png/5fa2dd/ffffff",
          "media6": "http://dummyimage.com/932x676.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam",
          "category": 2,
          "reqWeather": "mauvais",
          "dateBegin": "9/25/2020",
          "dateEnd": "8/6/2020",
          "eventAddress": "413 Daystar Hill",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Hénin-Beaumont",
          "eventLat": 50.3171905,
          "eventLong": 2.801236,
          "orgName": "SEACOR Holdings, Inc.",
          "orgAddress": "5034 Lighthouse Bay Junction",
          "orgStates": "Haute-Normandie",
          "orgCity": "Rouen",
          "orgPhone": "486 999 4020",
          "orgMail": "gjosephsond@arizona.edu",
          "infoGen": "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
          "infoTransp": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 48,
          "media1": "http://dummyimage.com/1422x557.png/dddddd/000000",
          "media2": "http://dummyimage.com/1325x734.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1823x811.png/dddddd/000000",
          "media4": "http://dummyimage.com/1423x1042.png/5fa2dd/ffffff",
          "media5": "http://dummyimage.com/936x710.png/5fa2dd/ffffff",
          "media6": "http://dummyimage.com/1782x664.png/5fa2dd/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo",
          "category": 1,
          "reqWeather": "mauvais",
          "dateBegin": "5/7/2021",
          "dateEnd": "1/5/2021",
          "eventAddress": "50187 Southridge Crossing",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Lille",
          "eventLat": 50.6091631,
          "eventLong": 3.2344605,
          "orgName": "First Trust Nasdaq Bank ETF",
          "orgAddress": "55259 Kennedy Place",
          "orgStates": "Haute-Normandie",
          "orgCity": "Rouen",
          "orgPhone": "635 747 1162",
          "orgMail": "dwynnee@deviantart.com",
          "infoGen": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
          "infoTransp": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
          "infoDog": true,
          "infoHandicap": false,
          "infoCost": 94,
          "media1": "http://dummyimage.com/1803x803.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/687x799.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1678x857.png/dddddd/000000",
          "media4": "http://dummyimage.com/1188x503.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/1684x513.png/dddddd/000000",
          "media6": "http://dummyimage.com/871x703.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum",
          "category": 3,
          "reqWeather": "neige",
          "dateBegin": "6/1/2020",
          "dateEnd": "12/25/2020",
          "eventAddress": "71 Pierstorff Pass",
          "eventStates": "Pays de la Loire",
          "eventCity": "Saint-Pierre-Montlimart",
          "eventLat": 47.2662587,
          "eventLong": -1.0263278,
          "orgName": "PIMCO New York Municipal Income Fund",
          "orgAddress": "1269 Farragut Circle",
          "orgStates": "Haute-Normandie",
          "orgCity": "Évreux",
          "orgPhone": "319 976 0718",
          "orgMail": "ppalffyf@soup.io",
          "infoGen": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
          "infoTransp": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
          "infoDog": true,
          "infoHandicap": true,
          "infoCost": 98,
          "media1": "http://dummyimage.com/1004x882.png/5fa2dd/ffffff",
          "media2": "http://dummyimage.com/1555x625.png/dddddd/000000",
          "media3": "http://dummyimage.com/1063x670.png/ff4444/ffffff",
          "media4": "http://dummyimage.com/1723x1037.png/dddddd/000000",
          "media5": "http://dummyimage.com/1793x714.png/5fa2dd/ffffff",
          "media6": "http://dummyimage.com/1837x870.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id",
          "category": 5,
          "reqWeather": "beau",
          "dateBegin": "7/18/2020",
          "dateEnd": "9/9/2020",
          "eventAddress": "6 Orin Place",
          "eventStates": "Pays de la Loire",
          "eventCity": "Saint-Herblain",
          "eventLat": 47.221906,
          "eventLong": -1.605738,
          "orgName": "First Trust Nasdaq Food & Beverage ETF",
          "orgAddress": "6 Mitchell Drive",
          "orgStates": "Basse-Normandie",
          "orgCity": "Bayeux",
          "orgPhone": "575 732 9188",
          "orgMail": "ioskehang@ucsd.edu",
          "infoGen": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
          "infoTransp": "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 94,
          "media1": "http://dummyimage.com/1529x848.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1239x1064.png/dddddd/000000",
          "media3": "http://dummyimage.com/897x617.png/ff4444/ffffff",
          "media4": "http://dummyimage.com/817x944.png/ff4444/ffffff",
          "media5": "http://dummyimage.com/799x740.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/742x918.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio",
          "category": 3,
          "reqWeather": "mauvais",
          "dateBegin": "5/16/2020",
          "dateEnd": "7/4/2021",
          "eventAddress": "6 Gulseth Plaza",
          "eventStates": "Pays de la Loire",
          "eventCity": "Clisson",
          "eventLat": 47.0799211,
          "eventLong": -1.2821339,
          "orgName": "Washington Prime Group Inc.",
          "orgAddress": "25640 Meadow Ridge Lane",
          "orgStates": "Basse-Normandie",
          "orgCity": "Caen",
          "orgPhone": "600 210 6285",
          "orgMail": "bcushionh@pbs.org",
          "infoGen": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.",
          "infoTransp": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 68,
          "media1": "http://dummyimage.com/1026x989.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1217x1047.png/dddddd/000000",
          "media3": "http://dummyimage.com/908x610.png/ff4444/ffffff",
          "media4": "http://dummyimage.com/1297x641.png/5fa2dd/ffffff",
          "media5": "http://dummyimage.com/1679x798.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/1619x744.png/5fa2dd/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor",
          "category": 2,
          "reqWeather": "mauvais",
          "dateBegin": "3/28/2021",
          "dateEnd": "1/20/2021",
          "eventAddress": "179 Victoria Junction",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Roubaix",
          "eventLat": 50.7022235,
          "eventLong": 3.1685214,
          "orgName": "NutriSystem Inc",
          "orgAddress": "99 Pine View Court",
          "orgStates": "Haute-Normandie",
          "orgCity": "Évreux",
          "orgPhone": "213 186 5371",
          "orgMail": "hpretori@homestead.com",
          "infoGen": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
          "infoTransp": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 54,
          "media1": "http://dummyimage.com/1552x963.png/dddddd/000000",
          "media2": "http://dummyimage.com/1850x619.png/5fa2dd/ffffff",
          "media3": "http://dummyimage.com/1696x749.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/765x530.png/5fa2dd/ffffff",
          "media5": "http://dummyimage.com/970x490.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/938x1004.png/ff4444/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec",
          "category": 5,
          "reqWeather": "neige",
          "dateBegin": "4/30/2020",
          "dateEnd": "10/12/2020",
          "eventAddress": "40661 Old Shore Crossing",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Boulogne-sur-Mer",
          "eventLat": 50.7308185,
          "eventLong": 1.5948224,
          "orgName": "The Hanover Insurance Group, Inc.",
          "orgAddress": "81877 Marcy Center",
          "orgStates": "Basse-Normandie",
          "orgCity": "Saint-Lô",
          "orgPhone": "702 388 3910",
          "orgMail": "keliassenj@hugedomains.com",
          "infoGen": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
          "infoTransp": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
          "infoDog": true,
          "infoHandicap": true,
          "infoCost": 98,
          "media1": "http://dummyimage.com/1603x615.png/cc0000/ffffff",
          "media2": "http://dummyimage.com/1176x874.png/cc0000/ffffff",
          "media3": "http://dummyimage.com/1005x797.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/977x747.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/1593x839.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/1859x598.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "aliquet maecenas leo odio condimentum id luctus nec molestie sed",
          "category": 5,
          "reqWeather": "mauvais",
          "dateBegin": "7/13/2020",
          "dateEnd": "5/19/2021",
          "eventAddress": "620 Melrose Terrace",
          "eventStates": "Pays de la Loire",
          "eventCity": "Sablé-sur-Sarthe",
          "eventLat": 47.8417718,
          "eventLong": -0.3419882,
          "orgName": "China Customer Relations Centers, Inc.",
          "orgAddress": "842 Londonderry Center",
          "orgStates": "Haute-Normandie",
          "orgCity": "Rouen",
          "orgPhone": "337 423 8446",
          "orgMail": "rsounessk@dot.gov",
          "infoGen": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
          "infoTransp": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
          "infoDog": true,
          "infoHandicap": true,
          "infoCost": 31,
          "media1": "http://dummyimage.com/1237x965.png/dddddd/000000",
          "media2": "http://dummyimage.com/702x773.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1139x691.png/dddddd/000000",
          "media4": "http://dummyimage.com/807x902.png/ff4444/ffffff",
          "media5": "http://dummyimage.com/1888x631.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/987x835.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in",
          "category": 1,
          "reqWeather": "mauvais",
          "dateBegin": "5/2/2021",
          "dateEnd": "8/12/2020",
          "eventAddress": "51 Pawling Alley",
          "eventStates": "New Jersey",
          "eventCity": "New Brunswick",
          "eventLat": 40.496654,
          "eventLong": -74.446092,
          "orgName": "Ennis, Inc.",
          "orgAddress": "2097 8th Alley",
          "orgStates": "Haute-Normandie",
          "orgCity": "Évreux",
          "orgPhone": "732 330 2584",
          "orgMail": "sskucel@usnews.com",
          "infoGen": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
          "infoTransp": "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
          "infoDog": true,
          "infoHandicap": true,
          "infoCost": 15,
          "media1": "http://dummyimage.com/1108x634.png/dddddd/000000",
          "media2": "http://dummyimage.com/1046x727.png/dddddd/000000",
          "media3": "http://dummyimage.com/1041x674.png/5fa2dd/ffffff",
          "media4": "http://dummyimage.com/1318x682.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/1202x517.png/dddddd/000000",
          "media6": "http://dummyimage.com/1760x518.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "in lacus curabitur at ipsum ac tellus semper interdum mauris",
          "category": 5,
          "reqWeather": "beau",
          "dateBegin": "2/9/2021",
          "dateEnd": "10/26/2020",
          "eventAddress": "780 Packers Court",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Valenciennes",
          "eventLat": 50.334011,
          "eventLong": 3.460955,
          "orgName": "BGC Partners, Inc.",
          "orgAddress": "4 Hoepker Avenue",
          "orgStates": "Basse-Normandie",
          "orgCity": "Flers",
          "orgPhone": "724 261 8321",
          "orgMail": "elaybournem@is.gd",
          "infoGen": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
          "infoTransp": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 43,
          "media1": "http://dummyimage.com/1783x739.png/cc0000/ffffff",
          "media2": "http://dummyimage.com/901x707.png/dddddd/000000",
          "media3": "http://dummyimage.com/1164x710.png/5fa2dd/ffffff",
          "media4": "http://dummyimage.com/879x577.png/ff4444/ffffff",
          "media5": "http://dummyimage.com/1094x584.png/5fa2dd/ffffff",
          "media6": "http://dummyimage.com/1188x739.png/5fa2dd/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "cras pellentesque volutpat dui maecenas tristique est et tempus semper est",
          "category": 1,
          "reqWeather": "mauvais",
          "dateBegin": "4/11/2021",
          "dateEnd": "11/9/2020",
          "eventAddress": "9484 Anderson Park",
          "eventStates": "New Jersey",
          "eventCity": "Newark",
          "eventLat": 40.7758541,
          "eventLong": -74.1650991,
          "orgName": "Del Frisco's Restaurant Group, Inc.",
          "orgAddress": "501 Continental Avenue",
          "orgStates": "Basse-Normandie",
          "orgCity": "Bayeux",
          "orgPhone": "973 104 7453",
          "orgMail": "vkebelln@comcast.net",
          "infoGen": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
          "infoTransp": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
          "infoDog": true,
          "infoHandicap": false,
          "infoCost": 55,
          "media1": "http://dummyimage.com/861x1006.png/cc0000/ffffff",
          "media2": "http://dummyimage.com/1776x949.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/958x869.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/1385x926.png/dddddd/000000",
          "media5": "http://dummyimage.com/1208x835.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/1840x746.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "ac enim in tempor turpis nec euismod scelerisque quam turpis",
          "category": 2,
          "reqWeather": "neige",
          "dateBegin": "6/20/2020",
          "dateEnd": "7/1/2020",
          "eventAddress": "65 Hollow Ridge Point",
          "eventStates": "Pays de la Loire",
          "eventCity": "Saint-Jean-de-Monts",
          "eventLat": 46.8260183,
          "eventLong": -2.1318548,
          "orgName": "HarborOne Bancorp, Inc.",
          "orgAddress": "63015 Dwight Circle",
          "orgStates": "Haute-Normandie",
          "orgCity": "Rouen",
          "orgPhone": "625 828 1074",
          "orgMail": "rbattino@nydailynews.com",
          "infoGen": "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
          "infoTransp": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 2,
          "media1": "http://dummyimage.com/1239x819.png/cc0000/ffffff",
          "media2": "http://dummyimage.com/1087x609.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/734x996.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/1338x907.png/dddddd/000000",
          "media5": "http://dummyimage.com/1619x480.png/5fa2dd/ffffff",
          "media6": "http://dummyimage.com/682x787.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas",
          "category": 1,
          "reqWeather": "neige",
          "dateBegin": "3/9/2021",
          "dateEnd": "6/25/2021",
          "eventAddress": "8 Surrey Lane",
          "eventStates": "New Jersey",
          "eventCity": "New Brunswick",
          "eventLat": 40.496654,
          "eventLong": -74.446092,
          "orgName": "TriState Capital Holdings, Inc.",
          "orgAddress": "1 Clarendon Junction",
          "orgStates": "Haute-Normandie",
          "orgCity": "Maromme",
          "orgPhone": "732 328 9074",
          "orgMail": "dkestellp@weebly.com",
          "infoGen": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
          "infoTransp": "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 45,
          "media1": "http://dummyimage.com/1648x972.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1088x886.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1415x1018.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/859x690.png/ff4444/ffffff",
          "media5": "http://dummyimage.com/1553x890.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/990x949.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit",
          "category": 3,
          "reqWeather": "mauvais",
          "dateBegin": "3/25/2021",
          "dateEnd": "4/12/2021",
          "eventAddress": "285 Luster Pass",
          "eventStates": "New Jersey",
          "eventCity": "Paterson",
          "eventLat": 40.9234909,
          "eventLong": -74.1797766,
          "orgName": "Morgan Stanley Emerging Markets Domestic Debt Fund, Inc.",
          "orgAddress": "98 Del Sol Hill",
          "orgStates": "Haute-Normandie",
          "orgCity": "Mont-Saint-Aignan",
          "orgPhone": "973 941 3660",
          "orgMail": "sderislyq@zdnet.com",
          "infoGen": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
          "infoTransp": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
          "infoDog": true,
          "infoHandicap": true,
          "infoCost": 87,
          "media1": "http://dummyimage.com/869x934.png/cc0000/ffffff",
          "media2": "http://dummyimage.com/988x828.png/dddddd/000000",
          "media3": "http://dummyimage.com/1236x825.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/891x484.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/1256x1018.png/5fa2dd/ffffff",
          "media6": "http://dummyimage.com/1314x1018.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt",
          "category": 4,
          "reqWeather": "mauvais",
          "dateBegin": "1/26/2021",
          "dateEnd": "8/26/2020",
          "eventAddress": "532 Steensland Way",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Maubeuge",
          "eventLat": 50.2748915,
          "eventLong": 3.9727365,
          "orgName": "Allied Healthcare Products, Inc.",
          "orgAddress": "7986 Cascade Junction",
          "orgStates": "Basse-Normandie",
          "orgCity": "Caen",
          "orgPhone": "246 445 9752",
          "orgMail": "kjuzar@networkadvertising.org",
          "infoGen": "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
          "infoTransp": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
          "infoDog": true,
          "infoHandicap": true,
          "infoCost": 98,
          "media1": "http://dummyimage.com/666x487.png/5fa2dd/ffffff",
          "media2": "http://dummyimage.com/1034x496.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1774x1056.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/1187x609.png/dddddd/000000",
          "media5": "http://dummyimage.com/1026x756.png/5fa2dd/ffffff",
          "media6": "http://dummyimage.com/890x575.png/5fa2dd/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse",
          "category": 1,
          "reqWeather": "neige",
          "dateBegin": "7/21/2020",
          "dateEnd": "8/16/2020",
          "eventAddress": "48 Chinook Plaza",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Lille",
          "eventLat": 44.1675867,
          "eventLong": 2.0308233,
          "orgName": "American Realty Investors, Inc.",
          "orgAddress": "00257 American Ash Plaza",
          "orgStates": "Basse-Normandie",
          "orgCity": "Alençon",
          "orgPhone": "508 275 0611",
          "orgMail": "rklazengas@newsvine.com",
          "infoGen": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
          "infoTransp": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 16,
          "media1": "http://dummyimage.com/1630x522.png/cc0000/ffffff",
          "media2": "http://dummyimage.com/642x1013.png/dddddd/000000",
          "media3": "http://dummyimage.com/1240x816.png/dddddd/000000",
          "media4": "http://dummyimage.com/1456x699.png/dddddd/000000",
          "media5": "http://dummyimage.com/1350x952.png/5fa2dd/ffffff",
          "media6": "http://dummyimage.com/1053x492.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna",
          "category": 2,
          "reqWeather": "neige",
          "dateBegin": "7/10/2021",
          "dateEnd": "6/19/2021",
          "eventAddress": "488 Dapin Hill",
          "eventStates": "Pays de la Loire",
          "eventCity": "La Chapelle-sur-Erdre",
          "eventLat": 47.3362701,
          "eventLong": -1.5349069,
          "orgName": "Hartford Financial Services Group, Inc. (The)",
          "orgAddress": "9 Thompson Court",
          "orgStates": "Haute-Normandie",
          "orgCity": "Le Havre",
          "orgPhone": "114 181 2495",
          "orgMail": "csustont@virginia.edu",
          "infoGen": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
          "infoTransp": "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
          "infoDog": true,
          "infoHandicap": false,
          "infoCost": 50,
          "media1": "http://dummyimage.com/1747x1052.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1515x866.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1626x623.png/dddddd/000000",
          "media4": "http://dummyimage.com/1002x991.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/930x1023.png/dddddd/000000",
          "media6": "http://dummyimage.com/1607x587.png/ff4444/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod",
          "category": 3,
          "reqWeather": "mauvais",
          "dateBegin": "8/26/2020",
          "dateEnd": "5/9/2020",
          "eventAddress": "46 Amoth Center",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Wasquehal",
          "eventLat": 50.6809584,
          "eventLong": 3.1233128,
          "orgName": "Vascular Biogenics Ltd.",
          "orgAddress": "773 Eagan Center",
          "orgStates": "Basse-Normandie",
          "orgCity": "Caen",
          "orgPhone": "233 643 5514",
          "orgMail": "htrevaskisu@bloglines.com",
          "infoGen": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
          "infoTransp": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 8,
          "media1": "http://dummyimage.com/645x895.png/5fa2dd/ffffff",
          "media2": "http://dummyimage.com/1636x553.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1286x779.png/ff4444/ffffff",
          "media4": "http://dummyimage.com/1340x785.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/1128x729.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/846x1049.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "felis ut at dolor quis odio consequat varius integer ac leo pellentesque",
          "category": 3,
          "reqWeather": "beau",
          "dateBegin": "12/22/2020",
          "dateEnd": "12/20/2020",
          "eventAddress": "9720 Washington Point",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Armentières",
          "eventLat": 47.5619629,
          "eventLong": -0.9147447,
          "orgName": "M III Acquisition Corp.",
          "orgAddress": "68 Homewood Pass",
          "orgStates": "Basse-Normandie",
          "orgCity": "Caen",
          "orgPhone": "276 862 5475",
          "orgMail": "chegdonnev@usda.gov",
          "infoGen": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
          "infoTransp": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 73,
          "media1": "http://dummyimage.com/1684x851.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1758x627.png/dddddd/000000",
          "media3": "http://dummyimage.com/956x609.png/dddddd/000000",
          "media4": "http://dummyimage.com/1238x699.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/1539x733.png/dddddd/000000",
          "media6": "http://dummyimage.com/1785x1063.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti",
          "category": 2,
          "reqWeather": "mauvais",
          "dateBegin": "11/20/2020",
          "dateEnd": "9/5/2020",
          "eventAddress": "61 American Lane",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Valenciennes",
          "eventLat": 50.334011,
          "eventLong": 3.460955,
          "orgName": "Thomson Reuters Corp",
          "orgAddress": "72 Haas Point",
          "orgStates": "Basse-Normandie",
          "orgCity": "Carpiquet",
          "orgPhone": "140 608 2427",
          "orgMail": "svannsw@shutterfly.com",
          "infoGen": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
          "infoTransp": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 84,
          "media1": "http://dummyimage.com/874x1048.png/cc0000/ffffff",
          "media2": "http://dummyimage.com/1525x624.png/cc0000/ffffff",
          "media3": "http://dummyimage.com/1004x734.png/5fa2dd/ffffff",
          "media4": "http://dummyimage.com/1679x826.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/713x1011.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/1896x617.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices",
          "category": 5,
          "reqWeather": "neige",
          "dateBegin": "4/11/2021",
          "dateEnd": "5/31/2021",
          "eventAddress": "66754 Carioca Place",
          "eventStates": "New Jersey",
          "eventCity": "Trenton",
          "eventLat": 40.1929685,
          "eventLong": -74.6502902,
          "orgName": "Dean Foods Company",
          "orgAddress": "8930 Moulton Point",
          "orgStates": "Basse-Normandie",
          "orgCity": "Caen",
          "orgPhone": "609 879 7914",
          "orgMail": "mfrickx@hexun.com",
          "infoGen": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
          "infoTransp": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 72,
          "media1": "http://dummyimage.com/1494x999.png/cc0000/ffffff",
          "media2": "http://dummyimage.com/1074x700.png/dddddd/000000",
          "media3": "http://dummyimage.com/1373x934.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/1445x779.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/701x557.png/dddddd/000000",
          "media6": "http://dummyimage.com/1596x833.png/ff4444/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede",
          "category": 1,
          "reqWeather": "neige",
          "dateBegin": "5/26/2020",
          "dateEnd": "3/12/2021",
          "eventAddress": "8 South Hill",
          "eventStates": "Pays de la Loire",
          "eventCity": "Cholet",
          "eventLat": 47.0615944,
          "eventLong": -0.8816138,
          "orgName": "Cerulean Pharma Inc.",
          "orgAddress": "01 Hazelcrest Court",
          "orgStates": "Haute-Normandie",
          "orgCity": "Saint-Étienne-du-Rouvray",
          "orgPhone": "640 772 4504",
          "orgMail": "aleony@google.nl",
          "infoGen": "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
          "infoTransp": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
          "infoDog": true,
          "infoHandicap": true,
          "infoCost": 15,
          "media1": "http://dummyimage.com/1568x755.png/5fa2dd/ffffff",
          "media2": "http://dummyimage.com/1270x1021.png/5fa2dd/ffffff",
          "media3": "http://dummyimage.com/810x963.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/1338x811.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/1174x780.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/965x490.png/5fa2dd/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id",
          "category": 3,
          "reqWeather": "mauvais",
          "dateBegin": "6/12/2021",
          "dateEnd": "2/19/2021",
          "eventAddress": "332 Nova Court",
          "eventStates": "Pays de la Loire",
          "eventCity": "Nantes",
          "eventLat": 47.2550409,
          "eventLong": -1.5401497,
          "orgName": "Torchmark Corporation",
          "orgAddress": "92 Burning Wood Plaza",
          "orgStates": "Basse-Normandie",
          "orgCity": "Coutances",
          "orgPhone": "554 359 2799",
          "orgMail": "bmendoncaz@i2i.jp",
          "infoGen": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
          "infoTransp": "Fusce consequat. Nulla nisl. Nunc nisl.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 40,
          "media1": "http://dummyimage.com/719x767.png/5fa2dd/ffffff",
          "media2": "http://dummyimage.com/866x666.png/5fa2dd/ffffff",
          "media3": "http://dummyimage.com/1087x920.png/5fa2dd/ffffff",
          "media4": "http://dummyimage.com/1593x762.png/ff4444/ffffff",
          "media5": "http://dummyimage.com/647x929.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/688x877.png/ff4444/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan",
          "category": 4,
          "reqWeather": "mauvais",
          "dateBegin": "1/28/2021",
          "dateEnd": "7/11/2020",
          "eventAddress": "10 Rieder Plaza",
          "eventStates": "New Jersey",
          "eventCity": "Newark",
          "eventLat": 40.7758541,
          "eventLong": -74.1650991,
          "orgName": "Dynegy Inc.",
          "orgAddress": "6 Declaration Terrace",
          "orgStates": "Haute-Normandie",
          "orgCity": "Pont-Audemer",
          "orgPhone": "973 196 4762",
          "orgMail": "abelfield10@jigsy.com",
          "infoGen": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
          "infoTransp": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 62,
          "media1": "http://dummyimage.com/1360x630.png/cc0000/ffffff",
          "media2": "http://dummyimage.com/895x674.png/dddddd/000000",
          "media3": "http://dummyimage.com/1652x481.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/1905x869.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/1009x807.png/5fa2dd/ffffff",
          "media6": "http://dummyimage.com/1232x501.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna",
          "category": 4,
          "reqWeather": "beau",
          "dateBegin": "7/11/2020",
          "dateEnd": "2/3/2021",
          "eventAddress": "18 Pawling Lane",
          "eventStates": "Pays de la Loire",
          "eventCity": "Montaigu",
          "eventLat": 48.1779574,
          "eventLong": -1.7555399,
          "orgName": "Cognex Corporation",
          "orgAddress": "829 Glendale Center",
          "orgStates": "Haute-Normandie",
          "orgCity": "Rouen",
          "orgPhone": "804 974 7137",
          "orgMail": "lpipe11@businesswire.com",
          "infoGen": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.",
          "infoTransp": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
          "infoDog": true,
          "infoHandicap": true,
          "infoCost": 64,
          "media1": "http://dummyimage.com/1343x890.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1907x573.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1210x740.png/ff4444/ffffff",
          "media4": "http://dummyimage.com/1633x513.png/5fa2dd/ffffff",
          "media5": "http://dummyimage.com/1808x926.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/944x780.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam",
          "category": 3,
          "reqWeather": "mauvais",
          "dateBegin": "8/6/2020",
          "dateEnd": "6/23/2021",
          "eventAddress": "7 Leroy Road",
          "eventStates": "Pays de la Loire",
          "eventCity": "Ancenis",
          "eventLat": 47.407461,
          "eventLong": -1.18752,
          "orgName": "Cummins Inc.",
          "orgAddress": "23451 Lakewood Court",
          "orgStates": "Haute-Normandie",
          "orgCity": "Le Havre",
          "orgPhone": "294 733 8036",
          "orgMail": "edavidge12@google.com.br",
          "infoGen": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
          "infoTransp": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
          "infoDog": true,
          "infoHandicap": true,
          "infoCost": 86,
          "media1": "http://dummyimage.com/1776x590.png/dddddd/000000",
          "media2": "http://dummyimage.com/1576x587.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1823x879.png/ff4444/ffffff",
          "media4": "http://dummyimage.com/770x850.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/1053x1068.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/799x619.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam",
          "category": 3,
          "reqWeather": "mauvais",
          "dateBegin": "9/15/2020",
          "dateEnd": "8/28/2020",
          "eventAddress": "6 Sutteridge Park",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Arras",
          "eventLat": 50.2837307,
          "eventLong": 2.7425682,
          "orgName": "Pulmatrix, Inc.",
          "orgAddress": "28 Mayer Crossing",
          "orgStates": "Haute-Normandie",
          "orgCity": "Bernay",
          "orgPhone": "326 541 4955",
          "orgMail": "lologhlen13@admin.ch",
          "infoGen": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
          "infoTransp": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 38,
          "media1": "http://dummyimage.com/1704x789.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1363x706.png/5fa2dd/ffffff",
          "media3": "http://dummyimage.com/1879x804.png/dddddd/000000",
          "media4": "http://dummyimage.com/1040x770.png/dddddd/000000",
          "media5": "http://dummyimage.com/822x806.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/1223x1021.png/5fa2dd/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum",
          "category": 2,
          "reqWeather": "mauvais",
          "dateBegin": "4/28/2021",
          "dateEnd": "6/16/2020",
          "eventAddress": "595 Sugar Alley",
          "eventStates": "Pays de la Loire",
          "eventCity": "Angers",
          "eventLat": 48.8693156,
          "eventLong": 2.3501981,
          "orgName": "Armstrong World Industries Inc",
          "orgAddress": "9915 Norway Maple Street",
          "orgStates": "Haute-Normandie",
          "orgCity": "Évreux",
          "orgPhone": "791 230 2772",
          "orgMail": "mdocksey14@odnoklassniki.ru",
          "infoGen": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
          "infoTransp": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
          "infoDog": false,
          "infoHandicap": false,
          "infoCost": 53,
          "media1": "http://dummyimage.com/649x682.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1730x602.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/1137x724.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/1557x640.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/669x1070.png/ff4444/ffffff",
          "media6": "http://dummyimage.com/1781x930.png/dddddd/000000",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "ipsum aliquam non mauris morbi non lectus aliquam sit amet diam",
          "category": 4,
          "reqWeather": "mauvais",
          "dateBegin": "3/28/2021",
          "dateEnd": "12/8/2020",
          "eventAddress": "3601 Luster Junction",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Arras",
          "eventLat": 50.2837307,
          "eventLong": 2.7425682,
          "orgName": "GRAVITY Co., Ltd.",
          "orgAddress": "64 Sunbrook Pass",
          "orgStates": "Basse-Normandie",
          "orgCity": "Coutances",
          "orgPhone": "945 630 7816",
          "orgMail": "cwillgoose15@joomla.org",
          "infoGen": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
          "infoTransp": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
          "infoDog": true,
          "infoHandicap": false,
          "infoCost": 39,
          "media1": "http://dummyimage.com/979x502.png/dddddd/000000",
          "media2": "http://dummyimage.com/1091x496.png/dddddd/000000",
          "media3": "http://dummyimage.com/861x599.png/dddddd/000000",
          "media4": "http://dummyimage.com/1000x881.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/1258x500.png/cc0000/ffffff",
          "media6": "http://dummyimage.com/1078x684.png/ff4444/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "amet diam in magna bibendum imperdiet nullam orci pede venenatis non",
          "category": 3,
          "reqWeather": "beau",
          "dateBegin": "6/17/2020",
          "dateEnd": "10/6/2020",
          "eventAddress": "96 Shoshone Point",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Dunkerque",
          "eventLat": 51.0515566,
          "eventLong": 2.3605584,
          "orgName": "ProAssurance Corporation",
          "orgAddress": "189 Jenifer Drive",
          "orgStates": "Haute-Normandie",
          "orgCity": "Évreux",
          "orgPhone": "780 239 4125",
          "orgMail": "lshucksmith16@bandcamp.com",
          "infoGen": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
          "infoTransp": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
          "infoDog": true,
          "infoHandicap": true,
          "infoCost": 68,
          "media1": "http://dummyimage.com/997x636.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1552x514.png/5fa2dd/ffffff",
          "media3": "http://dummyimage.com/1263x827.png/dddddd/000000",
          "media4": "http://dummyimage.com/1752x1013.png/ff4444/ffffff",
          "media5": "http://dummyimage.com/1417x548.png/dddddd/000000",
          "media6": "http://dummyimage.com/1683x591.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus",
          "category": 3,
          "reqWeather": "mauvais",
          "dateBegin": "9/25/2020",
          "dateEnd": "12/26/2020",
          "eventAddress": "966 Hovde Trail",
          "eventStates": "Pays de la Loire",
          "eventCity": "La Roche-sur-Yon",
          "eventLat": 46.6704712,
          "eventLong": -1.4244076,
          "orgName": "The Finish Line, Inc.",
          "orgAddress": "454 Portage Parkway",
          "orgStates": "Haute-Normandie",
          "orgCity": "Maromme",
          "orgPhone": "448 895 2772",
          "orgMail": "emonson17@gravatar.com",
          "infoGen": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
          "infoTransp": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 57,
          "media1": "http://dummyimage.com/874x873.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/701x480.png/ff4444/ffffff",
          "media3": "http://dummyimage.com/690x821.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/846x676.png/cc0000/ffffff",
          "media5": "http://dummyimage.com/944x610.png/dddddd/000000",
          "media6": "http://dummyimage.com/1398x1016.png/5fa2dd/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat",
          "category": 3,
          "reqWeather": "neige",
          "dateBegin": "3/11/2021",
          "dateEnd": "9/15/2020",
          "eventAddress": "94455 Sunnyside Plaza",
          "eventStates": "Pays de la Loire",
          "eventCity": "Angers",
          "eventLat": 47.4441206,
          "eventLong": -0.5572458,
          "orgName": "Greene County Bancorp, Inc.",
          "orgAddress": "69 Stone Corner Point",
          "orgStates": "Basse-Normandie",
          "orgCity": "Flers",
          "orgPhone": "635 728 7331",
          "orgMail": "alafford18@moonfruit.com",
          "infoGen": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
          "infoTransp": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 41,
          "media1": "http://dummyimage.com/694x826.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1772x598.png/cc0000/ffffff",
          "media3": "http://dummyimage.com/1071x822.png/dddddd/000000",
          "media4": "http://dummyimage.com/659x837.png/dddddd/000000",
          "media5": "http://dummyimage.com/969x937.png/dddddd/000000",
          "media6": "http://dummyimage.com/1369x1023.png/ff4444/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      },
      {
          "eventTitle": "elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas",
          "category": 5,
          "reqWeather": "beau",
          "dateBegin": "7/13/2020",
          "dateEnd": "2/17/2021",
          "eventAddress": "96 Sage Trail",
          "eventStates": "Nord-Pas-de-Calais",
          "eventCity": "Berck",
          "eventLat": 50.398362,
          "eventLong": 1.5608271,
          "orgName": "Invesco Credit Opportunities Fund",
          "orgAddress": "7999 Dixon Pass",
          "orgStates": "Haute-Normandie",
          "orgCity": "Dieppe",
          "orgPhone": "341 213 4469",
          "orgMail": "dbrislane19@addthis.com",
          "infoGen": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
          "infoTransp": "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
          "infoDog": false,
          "infoHandicap": true,
          "infoCost": 84,
          "media1": "http://dummyimage.com/687x1072.png/ff4444/ffffff",
          "media2": "http://dummyimage.com/1126x935.png/5fa2dd/ffffff",
          "media3": "http://dummyimage.com/1858x589.png/cc0000/ffffff",
          "media4": "http://dummyimage.com/720x788.png/dddddd/000000",
          "media5": "http://dummyimage.com/662x1022.png/5fa2dd/ffffff",
          "media6": "http://dummyimage.com/1808x1013.png/cc0000/ffffff",
          "rating": [
              {
                  "avgRating": 0,
                  "nbrRating": 0
              }
          ],
          "users": []
      }
  ]
   //insert your JsonList HERE! 
  constructor(
    private _afs: AngularFirestore
  ) {
    this._itemsCollection = this._afs.collection<any>('events');
  }
//copy this to file !!! the send start on page load make it just 1 time!!!
// this._jsonToFirestore.saveobjFirestore() --- dont forget to import the service

  async saveobjFirestore(){
    console.log('menu',this.fakeEvents);
   await this.fakeEvents.forEach(obj => {
      
     this._itemsCollection.add({
        eventTitle: obj.eventTitle,
        category: obj.category,
        eventDescr:"Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem." ,
        reqWeather: obj.reqWeather,
        dateBegin: obj.dateBegin,
        dateEnd: obj.dateEnd,
        eventAddress: obj.eventAddress,
        eventStates: obj.eventStates,
        eventCity: obj.eventCity,
        eventLat: obj.eventLat,
        eventLong: obj.eventLong,
        orgName: obj.orgName,
        orgAddress: obj.orgAddress,
        orgStates: obj.orgStates,
        orgCity: obj.orgCity,
        orgPhone: obj.orgPhone,
        orgMail: obj.orgMail,
        infoGen: obj.infoGen,
        infoTransp: obj.infoTransp,
        infoDog: obj.infoDog,
        infoHandicap: obj.infoHandicap,
        infoCost: obj.infoCost,
        media1: obj.media1,
        media2: obj.media2,
        media3: obj.media3,
        media4: obj.media4,
        media5: obj.media5,
        media6: obj.media6,
        ratings: [],
        users: []
      }).then(function (docRef) {
        console.log("Document written with ID: ", docRef.id);
      })
        .catch(function (error) {
          console.error("Error adding document: ", error);
        });
    });
  }



}



